spring.application.name=track-series-backend
spring.profiles.default=develop,local
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

# Database
spring.datasource.url=jdbc:mysql://${DB_HOST:${db.host:localhost}}:${DB_PORT:${db.port:3306}}/${DB_NAME:${db.name:track_series}}?serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:${db.username:root}}
spring.datasource.password=${DB_PASSWORD:${DB_ROOT_PASSWORD:${db.password:}}}
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false

# External APIs
tvmaze.api.base-url=https://api.tvmaze.com

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# JWT
application.security.jwt.expiration=86400000
application.security.jwt.secret-key=${JWT_SECRET:${LOCAL_JWT_SECRET:dev-secret-key-change-me}}


# Schedule
app.series-refresh.cron = 0 0 4 * * 1
app.series-refresh.delay-ms=1000

