spring.config.import=optional:file:.env.develop[.properties],optional:file:../.env.develop[.properties]

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.datasource.password=${DB_PASSWORD}
application.security.jwt.secret-key=${JWT_SECRET}

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
