spring.application.name=track-series-backend
spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# DB
spring.datasource.url=jdbc:mysql://${DB_HOST:${db.host:localhost}}:${DB_PORT:${db.port:3306}}/${DB_NAME:${db.name:track_series}}?serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:${db.username:root}}
spring.datasource.password=${DB_PASSWORD:${db.password}}
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
# api
tvmaze.api.base-url=https://api.tvmaze.com

# cors
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# jwt
application.security.jwt.expiration=86400000
application.security.jwt.secret-key=${JWT_SECRET:${application.security.jwt.secret-key:}}
